import "./globals.css";


export const metadata = {
  title: "Digital Invitation",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/assets/images/lovepik-short-message-linear-icon-png-image_400276993_wh1200.png"
        type="image/<generated>"
        sizes="<generated>"
      />
      <body className={` antialiased`}>
        {children}
      </body>
    </html>
  );
}
